<?php

declare(strict_types=1);

namespace App\Telegram\Types;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * The file generation process needs to be started by the application. Use setFileGenerationProgress and finishFileGeneration to generate the file
 */
class UpdateFileGenerationStart extends Update implements \JsonSerializable
{
    public function __construct(
        /** Unique identifier for the generation process */
        #[SerializedName('generation_id')]
        private int $generationId,
        /** The original path specified by the application in inputFileGenerated */
        #[SerializedName('original_path')]
        private string $originalPath,
        /** The path to a file that must be created and where the new file must be generated by the application. */
        #[SerializedName('destination_path')]
        private string $destinationPath,
        /** If the conversion is "#url#" than original_path contains an HTTP/HTTPS URL of a file that must be downloaded by the application. */
        #[SerializedName('conversion')]
        private string $conversion,
    ) {
    }

    /**
     * Get Unique identifier for the generation process
     */
    public function getGenerationId(): int
    {
        return $this->generationId;
    }

    /**
     * Set Unique identifier for the generation process
     */
    public function setGenerationId(int $generationId): self
    {
        $this->generationId = $generationId;

        return $this;
    }

    /**
     * Get The original path specified by the application in inputFileGenerated
     */
    public function getOriginalPath(): string
    {
        return $this->originalPath;
    }

    /**
     * Set The original path specified by the application in inputFileGenerated
     */
    public function setOriginalPath(string $originalPath): self
    {
        $this->originalPath = $originalPath;

        return $this;
    }

    /**
     * Get The path to a file that must be created and where the new file must be generated by the application.
     */
    public function getDestinationPath(): string
    {
        return $this->destinationPath;
    }

    /**
     * Set The path to a file that must be created and where the new file must be generated by the application.
     */
    public function setDestinationPath(string $destinationPath): self
    {
        $this->destinationPath = $destinationPath;

        return $this;
    }

    /**
     * Get If the conversion is "#url#" than original_path contains an HTTP/HTTPS URL of a file that must be downloaded by the application.
     */
    public function getConversion(): string
    {
        return $this->conversion;
    }

    /**
     * Set If the conversion is "#url#" than original_path contains an HTTP/HTTPS URL of a file that must be downloaded by the application.
     */
    public function setConversion(string $conversion): self
    {
        $this->conversion = $conversion;

        return $this;
    }

    public function jsonSerialize(): array
    {
        return [
            '@type' => 'updateFileGenerationStart',
            'generation_id' => $this->getGenerationId(),
            'original_path' => $this->getOriginalPath(),
            'destination_path' => $this->getDestinationPath(),
            'conversion' => $this->getConversion(),
        ];
    }
}
